### ISSUE TITLE
Readme is very confusing for someone without much context of project

### ISSUE THREAD

**Issue by thonmakerformvp** [abcnews/odyssey#12]
I have moderate experience in web dev but by no means am i an expert. I think this tech is really cool and the fact that it's open source is even cooler and gives it more potential. That said, the readme is really confusing and doesn't give me a clear way to start using this code. I think updating it with a good set of step by step instructions to get started would be great.

**Comment by colingourlay** [comment]
Hi @thonmakerformvp!

Thanks for the message. Odyssey is a project we developed specifically to enhance the look & interactive capabilities of our more ambitious stories on http://www.abc.net.au/news/, and isn't designed for use in any other environment.

We've open sourced this repository primarily so we can develop it in the open, and to allow those who want to poke around the source to pull out little nuggets of code that they find useful.

_That said_, we are working towards extracting some of the more useful general-purpose components—such as the task scheduler that gracefully handles UI scroll events—and releasing them as separate packages, with public-friendly documentation.

Once we get around to that, I'll be sure to reply here to let you know!

**Comment by phara23** [comment]
Any updates?
