### ISSUE TITLE
Full width videos on IE 11 and Edge aren't centered

### ISSUE THREAD

**Issue by phocks** [abcnews/odyssey#20]
Seems like the fix for the full-width video IE 11 bug introduced another bug in all browsers where the videos weren't being centered.

I managed to fix this in other browsers by only applying the styles to IE 11 and Edge with this code in the Odyssey fragment.

```
/* Internet Explorer 10+, Microsoft Edge Browser */
_:-ms-lang(x), .element { ... }
```

But the non-centering bug still remains in IE 11 and Edge. I can try to have a look at it otherwise maybe @nathanhoad or @colingourlay know of an easy fix.

**Comment by nathanhoad** [comment]
I've extended the IE specific rules to use `tranform`s to center the videos. It seems to work for now. We can have another look at it when Colin gets back.
