### ISSUE TITLE
Piece meal scrims have the wrong background blur level and also appear to be too transparent

### ISSUE THREAD

**Issue by BenSpraggon** [abcnews/odyssey#55]
![image](https://github.com/user-attachments/assets/31e3d2b6-8964-4788-bbae-6f5f9a808f76)

**Comment by drzax** [comment]
@BenSpraggon The opacity was incorrect — accidentally doubled. But the blur level is as per the design file (5px). Do you want to increase it?

**Comment by drzax** [comment]
Correct transparency applied in b08a9a9420b3f604f00aaa4c061978121c785577
