### ISSUE TITLE
Client height

### ISSUE THREAD

**Issue by drzax** [abcnews/odyssey#70]
I haven't actually seen a manifestation of this, but just reading the code, this line looks like a bug. Should `client.h` and `nextClient.h` here be `.height`?

https://github.com/abcnews/odyssey/blob/3cf86be303aa2ee4b692188a16f9e9e08225b18e/src/app/scheduler/index.js#L66

**Comment by colingourlay** [comment]
I reckon you're on to something. This would manifest if the a resize only changed the window height, which we would almost never see (seeing that size changes are usually to/from full screen or orientation changes).

**Comment by nathanhoad** [comment]
This explains something I did witness the other day with the election map - mobile UI appearing/disappearing wasn't registering as a resize when using the scheduler.
