### ISSUE TITLE
Use Odyssey in WordPress or Standard HTML site

### ISSUE THREAD

**Issue by noyaustralia2017** [abcnews/odyssey#93]
I am just new to learning HTML and web design. I like the style that Odyssey has on ABC News articles and I was just wondering is it possible to use the Odyssey design in a standard web page that is just made from HTML and can it be integrated into WordPress as well?

**Comment by drzax** [comment]
The short answer is no, unfortunately. The Odyssey format is developed specifically for the ABC News site and tied quite closely to its structure.

It's published here in the hope people might learn from it or find it useful in some other way, but it's not intended to be used outside the ABC website. So you're very welcome to dig into it if you want to find out how a particular feature is implemented.

If you're trying to implement something similar in WordPress, you'd be better off writing a WP theme that has some of the features than trying to somehow make it work on top of a WP theme.

**Comment by noyaustralia2017** [comment]
Thank you so much @drzax . That makes a lot of sense. Great work to you and the team on designing Odyssey - makes certain stories super engaging to see.
